#!/usr/bin/env bash
# Install nginx web server and basic setup
sudo apt-get update -y
sudo apt-get install nginx -y
# Adjust the firewall
# sudo ufw enable -y
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx HTTP'
# Take backup of the original index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/bkup_index.nginx-debian.html
# Changing to sudo for update the file
sudo su
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
