#!/usr/bin/env bash
# script that creates an RSA key pair with these requirements:
# Name of the created private key must be holberton
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty
ssh-keygen -t rsa -f holberton -b 4096 -N betty
